CREATE TABLE public."storage" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bucket_name varchar(255) NULL,
	"path" varchar(255) NULL,
	"type" varchar(255) NULL,
	CONSTRAINT storage_pkey PRIMARY KEY (id)
);