CREATE TABLE IF NOT EXISTS public."storage" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bucket_name varchar(255) NULL,
	"path" varchar(255) NULL,
	"type" varchar(255) NULL,
	CONSTRAINT storage_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.roles (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(20) NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(50) NULL,
	"password" varchar(120) NULL,
	username varchar(20) NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.user_roles (
	user_id int8 NOT NULL,
	role_id int4 NOT NULL,
	CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
	CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id),
	CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id)
);